# Generated by Django 4.2.2 on 2023-06-19 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='picture/post/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('model_result', models.CharField(blank=True, max_length=255, null=True)),
                ('pet_id', models.ForeignKey(db_column='PetID', on_delete=django.db.models.deletion.CASCADE, to='accounts.pet')),
                ('userid', models.ForeignKey(db_column='UserID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=32, null=True)),
                ('contents', models.CharField(blank=True, db_column='Contents', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pictureid', models.ForeignKey(db_column='PictureID', on_delete=django.db.models.deletion.CASCADE, to='posts.picture')),
                ('userid', models.ForeignKey(db_column='UserID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TItle', max_length=32)),
                ('contents', models.CharField(db_column='Contents', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionid', models.ForeignKey(db_column='Questionid', on_delete=django.db.models.deletion.CASCADE, to='posts.question')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
