# Generated by Django 4.1 on 2023-06-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hospital_user_id'),
        ('posts', '0002_alter_answer_created_at_alter_picture_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pet_id',
            field=models.ForeignKey(blank=True, db_column='PetID', on_delete=django.db.models.deletion.CASCADE, to='accounts.pet'),
        ),
    ]
