# Generated by Django 4.2.2 on 2023-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_picture_model_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='gpt_explain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='contents',
            field=models.TextField(db_column='Contents'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='model_conf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='contents',
            field=models.TextField(blank=True, db_column='Contents', null=True),
        ),
    ]
